[package]
name = "finance-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"]}
idgenerator = "2.0.0"
serde = { version = "1.0.215", features = ["derive"] }
bincode = "1.3.3"
